# Generated by Django 5.2.7 on 2026-04-08 13:28

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('acronym', models.CharField(max_length=24, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('preference_score', models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                'ordering': ['-preference_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_score', models.PositiveSmallIntegerField()),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('ME', 'Mechanical'), ('EE', 'Electrical'), ('EC', 'Electronics'), ('CE', 'Civil'), ('CH', 'Chemical'), ('IN', 'Instrumentation'), ('BT', 'Biotechnology'), ('XE', 'Engineering Sciences'), ('PI', 'Production')], max_length=8)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('GENERAL_PWD', 'General PwD'), ('OBC_NCL', 'OBC-NCL'), ('OBC_NCL_PWD', 'OBC-NCL PwD'), ('SC', 'SC'), ('SC_PWD', 'SC PwD'), ('ST', 'ST'), ('ST_PWD', 'ST PwD'), ('EWS', 'EWS'), ('EWS_PWD', 'EWS PwD')], max_length=12)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_paid', models.BooleanField(default=False)),
                ('results_snapshot', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(default='weekly', max_length=24)),
                ('razorpay_order_id', models.CharField(max_length=120, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_signature', models.CharField(blank=True, max_length=256)),
                ('amount_paise', models.PositiveIntegerField(default=1000)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.applicantsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('degree', models.CharField(default='M.Tech', max_length=80)),
                ('branch_code', models.CharField(choices=[('CS', 'Computer Science'), ('ME', 'Mechanical'), ('EE', 'Electrical'), ('EC', 'Electronics'), ('CE', 'Civil'), ('CH', 'Chemical'), ('IN', 'Instrumentation'), ('BT', 'Biotechnology'), ('XE', 'Engineering Sciences'), ('PI', 'Production')], max_length=8)),
                ('coap_rounds', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admissions.institute')),
            ],
            options={
                'ordering': ['institute__name', 'name'],
                'unique_together': {('institute', 'name', 'branch_code')},
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('GENERAL_PWD', 'General PwD'), ('OBC_NCL', 'OBC-NCL'), ('OBC_NCL_PWD', 'OBC-NCL PwD'), ('SC', 'SC'), ('SC_PWD', 'SC PwD'), ('ST', 'ST'), ('ST_PWD', 'ST PwD'), ('EWS', 'EWS'), ('EWS_PWD', 'EWS PwD')], max_length=12)),
                ('year', models.PositiveSmallIntegerField()),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metric_type', models.CharField(choices=[('score', 'Score'), ('marks', 'Marks')], default='score', max_length=8)),
                ('closing_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='admissions.program')),
            ],
            options={
                'ordering': ['-year', '-max_score'],
                'unique_together': {('program', 'category', 'year')},
            },
        ),
    ]
